<a href="https://colab.research.google.com/github/sadrireza/Neural-Networks/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.5.0+cu121'

## Tensor Initialization

### From Data

In [4]:
data = [[1.,2.],[3.,4.]]
type(data)

list

In [5]:
data_tensor = torch.tensor(data, dtype=torch.int32) #always uses a copy of our data
print(data_tensor)
print(data_tensor.dtype)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
torch.int32


### From Numpy Arrays

In [6]:
'''
while we are using this method, any change in tensor will lead to change in
numpy array and vice versa
'''

'\nwhile we are using this method, any change in tensor will lead to change in\nnumpy array and vice versa\n'

In [7]:
#torch.from_numpy()
data_array = np.array(data)
tensor_a = torch.from_numpy(data_array) #uses original data
print(tensor_a)
print(tensor_a.dtype)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
torch.float64


In [8]:
#torch.as_tensor()
tensor_b = torch.as_tensor(data) #uses original data
print(tensor_b)
print(tensor_b.dtype)

tensor([[1., 2.],
        [3., 4.]])
torch.float32


## With Random or Constant Values

In [9]:
#torch.zeros()
zeros_tensor = torch.zeros(size=(3,4)) #dtype is always float32 by default
print (zeros_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
#torch.ones()
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
torch.eye(3) #identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.4123, 0.1879, 0.4572, 0.4793],
        [0.1516, 0.2924, 0.2852, 0.6080],
        [0.4540, 0.5629, 0.7758, 0.3420]])

In [13]:
randn_tensor = torch.randn(3,4) #rand normal
randn_tensor

tensor([[ 0.3679, -0.2685,  0.5390,  0.0778],
        [-0.1120, -0.1437, -1.3962, -0.8699],
        [ 0.6206,  1.9942,  0.7525,  0.8611]])

In [14]:
randint_tensor = torch.randint(low=0, high=10, size=(3,4))
randint_tensor

tensor([[0, 4, 9, 7],
        [1, 2, 3, 2],
        [2, 0, 8, 2]])

In [15]:
base = [[1,2,3],[4,5,6],[7,8,9]]
base_tensor = torch.tensor(base, dtype = torch.float32)
base_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [16]:
randlike_tensor = torch.rand_like(base_tensor)
randlike_tensor #A random tensor with the length equal to base tensor

tensor([[0.3691, 0.2785, 0.5871],
        [0.5188, 0.9886, 0.6543],
        [0.5992, 0.6607, 0.4372]])

In [17]:
randint_like_tensor = torch.randint_like(base_tensor, low=0, high=10)
randint_like_tensor

tensor([[2., 5., 0.],
        [2., 9., 7.],
        [9., 2., 0.]])

In [18]:
zeros_like_tensor = torch.zeros_like(base_tensor)
zeros_like_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
ones_like_tensor = torch.ones_like(base_tensor)
ones_like_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
empty_tensor = torch.empty(4,4) #uninitialized tensor
empty_tensor #values we see are not our tensors values
#we see values in our tensor which are value of the memory while we are creating our tensor

tensor([[ 0.0000e+00,  0.0000e+00, -1.9761e-38,  3.1892e-41],
        [ 3.3246e+38,  3.1892e-41, -2.5608e-26,  4.3959e-41],
        [ 1.4013e-45,  0.0000e+00,  1.2612e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [21]:
A = torch.diag(torch.rand(3)) #diagonal tensor
A

tensor([[0.9496, 0.0000, 0.0000],
        [0.0000, 0.5232, 0.0000],
        [0.0000, 0.0000, 0.4362]])

## Creating Tensors from Ranges

In [22]:
#torch.arange()
#torch.linspace()

In [23]:
arange_tensor = torch.arange(5)
arange_tensor

tensor([0, 1, 2, 3, 4])

In [24]:
arange_tensor2 = torch.arange(0,10,2) #start point is inclusive
arange_tensor2 #end point is exclusive

tensor([0, 2, 4, 6, 8])

In [25]:
torch_arange3 = torch.arange(0,13,1.5, dtype=torch.float32)
torch_arange3

tensor([ 0.0000,  1.5000,  3.0000,  4.5000,  6.0000,  7.5000,  9.0000, 10.5000,
        12.0000])

In [26]:
linspace_tensor = torch.linspace(0,10, steps=5)
linspace_tensor

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [27]:
linspace_tensor2 = torch.linspace(0,11, steps=7, dtype=torch.float32)
linspace_tensor2

tensor([ 0.0000,  1.8333,  3.6667,  5.5000,  7.3333,  9.1667, 11.0000])

## Attributes

In [28]:
# tensor.shape()
# tensor.size()
#tensor.dtype()
#tensor.device()

In [29]:
my_tensor = torch.rand(3,4)
my_tensor

tensor([[0.6064, 0.7043, 0.4820, 0.7253],
        [0.1754, 0.2908, 0.3324, 0.5191],
        [0.6196, 0.4017, 0.3589, 0.1028]])

In [30]:
print(f'shape of my tensor is: {my_tensor.shape}')
print(f'size of my tensor is: {my_tensor.size()}')
print(f'dtype of my tensor is: {my_tensor.dtype}')
print(f'device of my tensor is: {my_tensor.device}')

shape of my tensor is: torch.Size([3, 4])
size of my tensor is: torch.Size([3, 4])
dtype of my tensor is: torch.float32
device of my tensor is: cpu


In [31]:
#How to change device
# my_tensor = my_tensor.to('cuda')
#or
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [32]:
'''
if we change our device to cuda, we can
transfer out tensor to cuda and vice versa
my_tensor = my_tensor.to(device)
'''

'\nif we change our device to cuda, we can\ntransfer out tensor to cuda and vice versa\nmy_tensor = my_tensor.to(device)\n'

In [33]:
!nvidia-smi #what is the cuda we are using

/bin/bash: line 1: nvidia-smi: command not found


## Operation on Tensors

### Indexing and Slicing

In [34]:
tensor = torch.randint(1,10, size=(4,4))
tensor

tensor([[7, 4, 6, 6],
        [5, 5, 7, 5],
        [4, 2, 3, 3],
        [5, 1, 7, 9]])

In [35]:
print(f'First row of tensor is: {tensor[0]}')
print(f'First column of tensor is: {tensor[:,0]}')
print(f'Last row of tensor is: {tensor[-1]}')
print(f'Last column of tensor is: {tensor[:,-1]}')
print(f'First 2 rows of tensor is: {tensor[:2]}')
print(f'First 2 columns of tensor is: {tensor[:,:2]}')
print(f'Last 2 rows of tensor is: {tensor[-2:]}')
print(f'Last 2 columns of tensor is: {tensor[:,-2:]}')
print(f'First 2 rows and 2 columns of tensor is: {tensor[:2,:2]}')
print(f'Last 2 rows and 2 columns of tensor is: {tensor[-2:,-2:]}')

First row of tensor is: tensor([7, 4, 6, 6])
First column of tensor is: tensor([7, 5, 4, 5])
Last row of tensor is: tensor([5, 1, 7, 9])
Last column of tensor is: tensor([6, 5, 3, 9])
First 2 rows of tensor is: tensor([[7, 4, 6, 6],
        [5, 5, 7, 5]])
First 2 columns of tensor is: tensor([[7, 4],
        [5, 5],
        [4, 2],
        [5, 1]])
Last 2 rows of tensor is: tensor([[4, 2, 3, 3],
        [5, 1, 7, 9]])
Last 2 columns of tensor is: tensor([[6, 6],
        [7, 5],
        [3, 3],
        [7, 9]])
First 2 rows and 2 columns of tensor is: tensor([[7, 4],
        [5, 5]])
Last 2 rows and 2 columns of tensor is: tensor([[3, 3],
        [7, 9]])


In [36]:
tensor[:-1,:-1]


tensor([[7, 4, 6],
        [5, 5, 7],
        [4, 2, 3]])

In [37]:
tensor[:, 2] = 20
tensor

tensor([[ 7,  4, 20,  6],
        [ 5,  5, 20,  5],
        [ 4,  2, 20,  3],
        [ 5,  1, 20,  9]])

### Joining Tensors

In [38]:
a = torch.randint(1,5, size=(3,3))
b = torch.randint(5,10, size=(3,3))
print(a)
print(b)

tensor([[4, 3, 3],
        [3, 4, 4],
        [2, 2, 1]])
tensor([[8, 5, 8],
        [6, 7, 6],
        [5, 5, 8]])


In [39]:
#torch.cat
cat_tensor = torch.cat((a,b), dim=0) #dim=0 means row wise
cat_tensor

tensor([[4, 3, 3],
        [3, 4, 4],
        [2, 2, 1],
        [8, 5, 8],
        [6, 7, 6],
        [5, 5, 8]])

In [40]:
#torch.stack
stack_tensor = torch.stack((a,b), dim=0)
stack_tensor

tensor([[[4, 3, 3],
         [3, 4, 4],
         [2, 2, 1]],

        [[8, 5, 8],
         [6, 7, 6],
         [5, 5, 8]]])

### Reshaping a Tensor

In [41]:
#torch.view
x = torch.rand(9)
x

tensor([0.2094, 0.3991, 0.8979, 0.8951, 0.1849, 0.2055, 0.1361, 0.8721, 0.6508])

In [42]:
y = x.view(3,3)
y

tensor([[0.2094, 0.3991, 0.8979],
        [0.8951, 0.1849, 0.2055],
        [0.1361, 0.8721, 0.6508]])

In [43]:
#torch.reshape
a = torch.arange(4)
a

tensor([0, 1, 2, 3])

In [44]:
b = a.reshape(2,2)
b

tensor([[0, 1],
        [2, 3]])

In [45]:
''' The difference between view and reshape:
reshape is done on a copy of our tensor
view is done on our original tensor
so reshape is safer than view
'''

' The difference between view and reshape:\nreshape is done on a copy of our tensor\nview is done on our original tensor\nso reshape is safer than view\n'

In [46]:
#torch.view_as
a = torch.arange(9)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
#torch.view_as uses a tensor as input
a = torch.arange(9)  # Create a tensor with values 0-8
b = a.view_as(y) # Reshape 'a' to match the shape of y
print(b)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


### Arithmetic Operations

In [56]:
tensor_a = torch.tensor([[1,1],[3,4]])
tensor_b = torch.tensor([[0,6],[7,1]])

In [57]:
#Addition
print (torch.add(tensor_a, tensor_b))

tensor([[ 1,  7],
        [10,  5]])


In [58]:
#Addition
print (tensor_a + tensor_b)

tensor([[ 1,  7],
        [10,  5]])


In [59]:
#Subtraction
print (torch.sub(tensor_a, tensor_b))

tensor([[ 1, -5],
        [-4,  3]])


In [60]:
#Subtraction
print (tensor_a - tensor_b)

tensor([[ 1, -5],
        [-4,  3]])


In [61]:
#Multiplication
print (torch.mul(tensor_a, tensor_b))

tensor([[ 0,  6],
        [21,  4]])


In [62]:
#Multtiplication
print (tensor_a * tensor_b)

tensor([[ 0,  6],
        [21,  4]])


In [63]:
#Divition
print (torch.div(tensor_a, tensor_b))

tensor([[   inf, 0.1667],
        [0.4286, 4.0000]])


In [64]:
#Divition
print (tensor_a / tensor_b)

tensor([[   inf, 0.1667],
        [0.4286, 4.0000]])


In [96]:
#Exponent
print (torch.pow(tensor_a, tensor_b))

tensor([[   1,    1],
        [2187,    4]])
tensor([[1, 1],
        [3, 4]])


In [66]:
#Exponent
print (tensor_a ** tensor_b)

tensor([[   1,    1],
        [2187,    4]])


In [67]:
#Matrix Multiplication
print (torch.mm(tensor_a, tensor_b))

tensor([[ 7,  7],
        [28, 22]])


In [68]:
#Matrix Multiplication
my_tensor = tensor_a @ tensor_b
my_tensor

tensor([[ 7,  7],
        [28, 22]])

In [69]:
#Matrix Multiplication
my_tensor = tensor_a.mm(tensor_b)
my_tensor

tensor([[ 7,  7],
        [28, 22]])

In [70]:
#Matrix Multiplication
my_tensor = tensor_a.matmul(tensor_b)
my_tensor

tensor([[ 7,  7],
        [28, 22]])

In [76]:
#Matrix Multiplication
my_tensor = torch.matmul(tensor_a, tensor_b)
my_tensor

tensor([[ 7,  7],
        [28, 22]])

### Single Element Tensors

In [80]:
#torch.item()
my_tensor = torch.randint(1,5, size=(4,4,))
my_tensor

tensor([[3, 4, 4, 4],
        [1, 2, 3, 3],
        [2, 3, 3, 2],
        [1, 1, 4, 2]])

In [81]:
agg = my_tensor.sum()
agg

tensor(42)

In [86]:
agg_item = agg.item() #returning a paython integer
print (agg_item, type(agg_item))

42 <class 'int'>


## In-Place Operations

In [91]:
#in place operations are done in the place, so memory is less used
#but they are not recommended because they change the original memory
x = torch.rand(3,3)
y = torch.rand(3,3)
print(x)
print(y)

tensor([[0.7601, 0.0304, 0.2534],
        [0.5449, 0.8154, 0.3944],
        [0.2379, 0.2674, 0.8355]])
tensor([[0.8066, 0.2962, 0.1927],
        [0.9848, 0.3947, 0.2096],
        [0.3238, 0.5810, 0.0409]])


In [94]:
#Normal Addirtion
print (x + y)
print (x) #x is not changed

tensor([[2.3732, 0.6228, 0.6387],
        [2.5145, 1.6049, 0.8136],
        [0.8855, 1.4294, 0.9172]])
tensor([[1.5667, 0.3266, 0.4460],
        [1.5297, 1.2102, 0.6040],
        [0.5617, 0.8484, 0.8763]])


In [95]:
#In-place Addition
#the structure is like a underline after add so: x.add_()
print (x.add_(y))
print (x) #x is changed

tensor([[2.3732, 0.6228, 0.6387],
        [2.5145, 1.6049, 0.8136],
        [0.8855, 1.4294, 0.9172]])
tensor([[2.3732, 0.6228, 0.6387],
        [2.5145, 1.6049, 0.8136],
        [0.8855, 1.4294, 0.9172]])


## Other Operations


*   Common Functions
*   Triginimetric Functions
*   Bitwise Operations
*   Comparison Operations
*   Reduction Operations
*   Linear Algebra Operations


Commands
1.   torch.max() min sum abs argmax arg min sqrt exp
2.   torch.norm()
3.torch.eq()
4.torch.mean()
5.torch.clamp()
6.torch.sort()
7.torch.any() all() unique()
8.torch.ndimension()
9.torch.remainder()
10.torch.numel()
11.torch.clone()
12.torch.squeeze()
13.torch.unsqueeze()
14.torch.t()


In [97]:
# prompt: torch.norm()
# torch.eq()
# torch.mean()
# torch.clamp()
# torch.sort()
# torch.any()
# torch.ndimension()
# torch.remainder()
# torch.numel()
# torch.clone()
# torch.squeeze()

# Example tensor
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# torch.norm() - Calculates the matrix norm or vector norm
norm_x = torch.norm(x)
print(f"Norm of x: {norm_x}")

# torch.eq() - Element-wise equality comparison
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 4])
equality = torch.eq(a, b)
print(f"Element-wise equality of a and b: {equality}")

# torch.mean() - Calculates the mean of all elements in the tensor
mean_x = torch.mean(x)
print(f"Mean of x: {mean_x}")

# torch.clamp() - Clamps all elements in input into the range [ min, max ]
clamped_x = torch.clamp(x, min=2.0, max=5.0)
print(f"Clamped x: {clamped_x}")

# torch.sort() - Sorts the elements of the input tensor along a given dimension
sorted_x, indices = torch.sort(x, dim=0)  # Sort along the columns (dim=0)
print(f"Sorted x: {sorted_x}")
print(f"Indices of sorted elements: {indices}")

# torch.any() - Returns True if any element in the input tensor is True
has_true = torch.any(x > 4)
print(f"Any element greater than 4: {has_true}")

# torch.ndimension() - Returns the number of dimensions of a tensor
dimensions = x.ndimension()
print(f"Number of dimensions in x: {dimensions}")

# torch.remainder() - Computes element-wise remainder of division
remainder = torch.remainder(x, 2) #Equivalent to x % 2
print(f"Remainder of x when divided by 2: {remainder}")

# torch.numel() - Returns the total number of elements in the input tensor
num_elements = x.numel()
print(f"Number of elements in x: {num_elements}")

# torch.clone() - Returns a copy of the tensor
x_clone = x.clone()
print(f"Clone of x: {x_clone}")


# torch.squeeze() - Returns a tensor with all the dimensions of input of size 1 removed
y = torch.rand(1,2,1,3)
y_squeezed = torch.squeeze(y)
print(f"Original tensor shape:{y.shape}")
print(f"Squeezed tensor shape: {y_squeezed.shape}")

Norm of x: 9.539392471313477
Element-wise equality of a and b: tensor([ True,  True, False])
Mean of x: 3.5
Clamped x: tensor([[2., 2., 3.],
        [4., 5., 5.]])
Sorted x: tensor([[1., 2., 3.],
        [4., 5., 6.]])
Indices of sorted elements: tensor([[0, 0, 0],
        [1, 1, 1]])
Any element greater than 4: True
Number of dimensions in x: 2
Remainder of x when divided by 2: tensor([[1., 0., 1.],
        [0., 1., 0.]])
Number of elements in x: 6
Clone of x: tensor([[1., 2., 3.],
        [4., 5., 6.]])
Original tensor shape:torch.Size([1, 2, 1, 3])
Squeezed tensor shape: torch.Size([2, 3])


In [98]:
#torch.unsqueeze()
x = torch.tensor([1, 2, 3, 4])
print(x.shape)  # Output: torch.Size([4])
x_unsqueezed = torch.unsqueeze(x, dim=0)  # Add a dimension at the beginning
print(x_unsqueezed.shape)  # Output: torch.Size([1, 4])
x_unsqueezed = torch.unsqueeze(x, dim=1)  # Add a dimension at the index 1
print(x_unsqueezed.shape)  # Output: torch.Size([4, 1])


#torch.t()  (transpose)
x = torch.randn(2, 3)
print(x)
print(x.t()) # Transpose of a matrix

#Example with a 3D tensor
x = torch.randn(2, 3, 4)
print(x.shape)
print(x.transpose(0,1).shape)

torch.Size([4])
torch.Size([1, 4])
torch.Size([4, 1])
tensor([[0.5386, 0.2928, 0.4202],
        [0.9750, 0.7833, 0.0474]])
tensor([[0.5386, 0.9750],
        [0.2928, 0.7833],
        [0.4202, 0.0474]])
torch.Size([2, 3, 4])
torch.Size([3, 2, 4])


In [99]:
# tensor
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], requires_grad=True)

# Normal copy
x_copy = x.clone()

# Modifying the copy
x_copy[0, 0] = 99.0

# Check if the original tensor is affected
print("Original tensor (x):", x)
print("Copied tensor (x_copy):", x_copy)


# detach() without gradient consideration
x_detached = x.detach()
x_detached[0,0] = 100

# check if original tensor is affected
print("Original tensor (x):",x)
print("Detached tensor (x_detached):",x_detached)

# detach() with gradient consideration

x_detached_grad = x.detach().clone() #this creates a new tensor so original will not be affected


x_detached_grad[0,0] = 101


#check if the original tensor is affected
print("Original tensor (x):",x)
print("Detached tensor (x_detached_grad):",x_detached_grad)

Original tensor (x): tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
Copied tensor (x_copy): tensor([[99.,  2.,  3.],
        [ 4.,  5.,  6.]], grad_fn=<CopySlices>)
Original tensor (x): tensor([[100.,   2.,   3.],
        [  4.,   5.,   6.]], requires_grad=True)
Detached tensor (x_detached): tensor([[100.,   2.,   3.],
        [  4.,   5.,   6.]])
Original tensor (x): tensor([[100.,   2.,   3.],
        [  4.,   5.,   6.]], requires_grad=True)
Detached tensor (x_detached_grad): tensor([[101.,   2.,   3.],
        [  4.,   5.,   6.]])


In [101]:
# requires_grad is an attribute of a tensor that indicates whether gradients should be computed for it during backpropagation.

# When requires_grad is set to True:
# - PyTorch will track all operations performed on the tensor.
# - Gradients with respect to the tensor can be computed using the .backward() method.
# - This is essential for training neural networks, where we need to calculate gradients to update model parameters.

# When requires_grad is set to False (default):
# - PyTorch will not track operations on the tensor.
# - Gradients cannot be computed for the tensor.
# - This is useful for tensors that represent input data or model parameters that should not be updated during training.


# Create a tensor with requires_grad=True
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# Perform some operations
y = x * 2
z = y.sum()

# Compute gradients
z.backward()

# Access the gradients
print(x.grad)  # Output: tensor([2., 2., 2.])


# detach() creates a new tensor that shares the same data but does not require gradients.
#This is crucial when you need to perform operations on a tensor without affecting the computational graph.

# detach() without gradient consideration
x_detached = x.detach()
x_detached[0] = 100 # Changing x_detached does not affect x because they are separate tensors

# check if original tensor is affected
print("Original tensor (x):",x)
print("Detached tensor (x_detached):",x_detached)

# detach() with gradient consideration
x_detached_grad = x.detach().clone() # This creates a copy which is independent of original tensor
x_detached_grad[0] = 101

#check if the original tensor is affected
print("Original tensor (x):",x)
print("Detached tensor (x_detached_grad):",x_detached_grad)

tensor([2., 2., 2.])
Original tensor (x): tensor([100.,   2.,   3.], requires_grad=True)
Detached tensor (x_detached): tensor([100.,   2.,   3.])
Original tensor (x): tensor([100.,   2.,   3.], requires_grad=True)
Detached tensor (x_detached_grad): tensor([101.,   2.,   3.])


In [ ]:
'''
Pytorch library expects you to enter batches of data.
so you usually have images with dimensions like
colors x height x width. But input required by
pytorch i like batch_size x colors x height x width.
so how should we change the shape of our tensor?
using torch.permute() and also torch.transpose()
and torch.swapaxes() and torch.unsqueeze()
'''

In [102]:
a = torch.rand(3,224,224)
a.shape

torch.Size([3, 224, 224])

In [105]:
b = a.unsqueeze(0) #one dimension is added to tensor
b.shape

torch.Size([1, 3, 224, 224])

In [107]:
c = torch.rand(1,1,1,1,1)
print(c)

tensor([[[[[0.0741]]]]])


In [109]:
a = torch.rand(1,20)
print(a)
print(a.shape)

tensor([[0.7166, 0.2434, 0.8731, 0.3286, 0.1843, 0.2800, 0.2981, 0.8268, 0.1605,
         0.5768, 0.7231, 0.5465, 0.7773, 0.1691, 0.7812, 0.0838, 0.7026, 0.2007,
         0.8387, 0.5509]])
torch.Size([1, 20])


In [110]:
b = a.squeeze(0) #one dimension is removed from tensor
print(b)
print(b.shape)

tensor([0.7166, 0.2434, 0.8731, 0.3286, 0.1843, 0.2800, 0.2981, 0.8268, 0.1605,
        0.5768, 0.7231, 0.5465, 0.7773, 0.1691, 0.7812, 0.0838, 0.7026, 0.2007,
        0.8387, 0.5509])
torch.Size([20])


## Interopearability
###Connections between numpy and pytorch

In [112]:
#numpy array to pytorch tensor
array = np.ones((2,3))
print(f'numpy array: {array}')

tensor = torch.from_numpy(array)
print(f'tensor: {tensor}')

numpy array: [[1. 1. 1.]
 [1. 1. 1.]]
tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [113]:
#pytoch tensor to numpy array
pytorch_rand = torch.rand(2,3)
print(f'pytorch tensor: {pytorch_rand}')

numpy_rand = pytorch_rand.numpy()
print(f'numpy array: {numpy_rand}')

pytorch tensor: tensor([[0.4911, 0.7413, 0.2093],
        [0.4238, 0.2093, 0.6063]])
numpy array: [[0.49105692 0.74127483 0.20928264]
 [0.42381197 0.20925552 0.6063445 ]]
